// <auto-generated />
using FootballManagement.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FootballManagement.Migrations
{
    [DbContext(typeof(FussballmannschaftDB))]
    [Migration("20230708171302_DbCreated")]
    partial class DbCreated
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FootballManagement.Model.Fussballmannschaft", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Fussballmannschaft");
                });

            modelBuilder.Entity("FootballManagement.Model.Spieler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nachname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vorname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Spieler");
                });

            modelBuilder.Entity("FussballmannschaftSpieler", b =>
                {
                    b.Property<int>("FussballmannschaftId")
                        .HasColumnType("int");

                    b.Property<int>("SpielerId")
                        .HasColumnType("int");

                    b.HasKey("FussballmannschaftId", "SpielerId");

                    b.HasIndex("SpielerId");

                    b.ToTable("FussballmannschaftSpieler");
                });

            modelBuilder.Entity("FussballmannschaftSpieler", b =>
                {
                    b.HasOne("FootballManagement.Model.Fussballmannschaft", null)
                        .WithMany()
                        .HasForeignKey("FussballmannschaftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FootballManagement.Model.Spieler", null)
                        .WithMany()
                        .HasForeignKey("SpielerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
